use_frameworks!

platform :ios, '9.0'

target 'FYFTableCollectionMiddleWare_Example' do
  pod 'FYFTableCollectionMiddleWare', :path => '../'

  target 'FYFTableCollectionMiddleWare_Tests' do
    inherit! :search_paths

    
  end
end
